import { expect, test } from "@playwright/test";

test("boss: launch day", async ({ page }, info) => {
  test.setTimeout(300_000);
  const shot = (n: string) => page.screenshot({ path: `e2e/__shots__/boss-${n}-${info.project.name}.png` });
  await page.goto("/dev/seed");
  await page.getByRole("button", { name: /chapter 1 done/i }).click();
  await expect(page.getByText(/seeded/)).toBeVisible();
  await page.goto("/campaign/a1");
  await page.waitForTimeout(1500);
  await page.keyboard.press("Escape");
  await page.waitForTimeout(500);
  await shot("0-chapter");
  await page.getByRole("button", { name: /start the launch/i }).click();
  await page.waitForTimeout(1200);
  await shot("1-intro");
  await page.getByRole("button", { name: /skip/i }).click();
  await page.waitForTimeout(800);
  // design: 7 × large, 16 workers, least outstanding + ejection, signed cookie
  await page.getByRole("radio", { name: /^large$/i }).click();
  const count = page.getByRole("slider", { name: /how many/i });
  await count.focus();
  for (let i = 0; i < 5; i++) await page.keyboard.press("ArrowRight");
  const workers = page.getByRole("slider", { name: /gunicorn workers per box/i });
  await workers.focus();
  for (let i = 0; i < 11; i++) await page.keyboard.press("ArrowRight");
  await page.getByRole("button", { name: /least outstanding/i }).click();
  await page.getByRole("checkbox", { name: /passive ejection/i }).check();
  await page.getByRole("button", { name: /signed cookie/i }).click();
  await shot("2-design");
  const fc = page.getByRole("slider", { name: /forecast/i });
  await fc.focus();
  await page.keyboard.press("ArrowLeft");
  await page.getByRole("radio", { name: /50%/ }).click();
  await page.getByRole("button", { name: /lock the forecast/i }).click();
  await page.getByRole("button", { name: /go live/i }).click();
  await page.waitForTimeout(30_000);
  await shot("3-fight");
  await expect(page.getByRole("button", { name: /^debrief$/i })).toBeVisible({ timeout: 120_000 });
  await shot("4-won");
  await page.getByRole("button", { name: /^debrief$/i }).click();
  await page.getByRole("textbox", { name: /your explanation/i }).fill("Sized for the spike with headroom, sixteen workers per box from Little's law, seven boxes so one crash is a seventh, least outstanding plus ejection, cookie sessions.");
  await page.getByRole("button", { name: /^submit$/i }).click();
  const met = page.getByRole("button", { name: /^met$/i });
  await expect(met.first()).toBeVisible({ timeout: 15_000 });
  for (let i = 0; i < (await met.count()); i++) await met.nth(i).click();
  await page.getByRole("button", { name: /continue/i }).click();
  await page.waitForTimeout(1500);
  await shot("5-rankup");
  await page.getByRole("button", { name: /skip/i }).click().catch(() => undefined);
  await page.waitForTimeout(1500);
  await shot("6-debrief");
  await expect(page.getByText(/boss survived/i).first()).toBeVisible();
});
