import { expect, test } from "@playwright/test";
import { skipIntro } from "./helpers";

test("incident room: the fourth box", async ({ page }, info) => {
  test.setTimeout(300_000);
  const shot = (n: string) => page.screenshot({ path: `e2e/__shots__/inc-${n}-${info.project.name}.png` });
  await page.goto("/dev/seed");
  await page.getByRole("button", { name: /chapter 1 done/i }).click();
  await expect(page.getByText(/seeded/)).toBeVisible();
  await page.goto("/incident");
  await skipIntro(page);
  await shot("0-list");
  await page.getByRole("button", { name: /take the page/i }).click();
  await page.waitForTimeout(1500);
  await shot("1-page");
  await page.getByRole("button", { name: /skip/i }).click();
  await page.waitForTimeout(4000);
  await shot("2-dash");
  await page.getByRole("tab", { name: /logs/i }).click();
  await page.getByRole("textbox", { name: /search logs/i }).fill("Booting");
  await page.waitForTimeout(500);
  await shot("3-logs");
  await page.getByRole("button", { name: /^pin$/i }).first().click();
  await page.getByRole("tab", { name: /hosts/i }).click();
  await page.getByRole("tab", { name: /app-4/i }).click();
  await page.getByRole("button", { name: /ps aux/i }).click();
  await page.getByRole("button", { name: /cat \/etc\/pigeon/i }).click();
  await page.waitForTimeout(400);
  await shot("4-hosts");
  await page.getByRole("button", { name: /^pin$/i }).first().click();
  await page.getByRole("button", { name: /one gunicorn worker/i }).click();
  await page.getByRole("radio", { name: /4×/ }).click();
  await page.getByRole("button", { name: /deregister app-4/i }).click();
  await page.getByRole("button", { name: /deregister app-4/i }).click();
  await expect(page.getByRole("button", { name: /resolve and write/i })).toBeEnabled({ timeout: 120_000 });
  await page.getByRole("tab", { name: /dashboards/i }).click();
  await page.waitForTimeout(1000);
  await shot("5-recovered");
  await page.getByRole("button", { name: /resolve and write/i }).click();
  const areas = page.locator("textarea");
  await areas.nth(0).fill("About a quarter of checkouts timed out for roughly three minutes after app-4 joined.");
  await areas.nth(1).fill("app-4 launched from template v7 without WEB_CONCURRENCY, so gunicorn ran one worker and its queue grew.");
  await areas.nth(2).fill("Health check through gunicorn, validate worker count at boot, alarm on per-target latency.");
  await page.getByRole("button", { name: /file the postmortem/i }).click();
  const met = page.getByRole("button", { name: /^met$/i });
  await expect(met.first()).toBeVisible({ timeout: 15_000 });
  for (let i = 0; i < (await met.count()); i++) await met.nth(i).click();
  await page.getByRole("button", { name: /record my grade/i }).click();
  await expect(page.getByText(/INC-0001 resolved/i)).toBeVisible();
  await page.waitForTimeout(1500);
  await shot("6-score");
});
